name: Docker Image CI

on:
  push:
    branches: ['main']
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image using Docker Compose
        run: |
          # Define image tags
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/to-do-ui-server
          IMAGE_TAG=${{ github.sha }}

          # Build the image using Docker Compose
          docker-compose -f docker-compose.yaml build

          # Tag the image with both 'latest' and the commit SHA
          docker tag to-do-ui-server:latest $IMAGE_NAME:latest
          docker tag to-do-ui-server:latest $IMAGE_NAME:$IMAGE_TAG

          # Push both tags to Docker Hub
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Verify Docker image
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/to-do-server-server:latest echo "Image built and pushed successfully"
